import {StyleSheet} from 'react-native';
import {SpoqaHanSansNeo} from 'src/styles';
import {fp, hp, wp} from 'src/utils';

export const styles = StyleSheet.create({
  homeScreenWrapper: {
    marginBottom: wp(-8),
    padding: wp(27),
    borderRadius: 17,
    borderBottomColor: '#F0F0F0',
    borderBottomWidth: 1,
    borderStartColor: '#F0F0F0',
    borderStartWidth: 1,
    borderEndColor: '#F0F0F0',
    borderEndWidth: 1,
  },
  homeScreenHeaderWrapper: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  homeScreenHeaderProfileWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  homeScreenHeaderRegionWrapper: {
    flexDirection: 'row',
  },
  homeScreenHeaderRegion: {
    fontSize: fp(17),
    fontFamily: SpoqaHanSansNeo.bold,
    color: 'black',
    justifyContent: 'center',
    alignItems: 'center',
  },
  homeScreenHeaderMapPinIcon: {
    width: wp(25),
    height: hp(25),
    marginRight: wp(3),
    marginLeft: wp(-8),
  },
  homeScreenHeaderProfileIcon: {
    width: wp(24),
    height: hp(24),
    borderRadius: 44 / 2,
    marginRight: wp(6),
  },
  homeScreenHeaderProfileUserName: {
    fontSize: fp(16),
    fontFamily: SpoqaHanSansNeo.bold,
    color: 'black',
  },
  homeScreenOptionWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: hp(14),
  },
  homeScreenOptionButton: {
    marginRight: wp(17),
  },
  homeScreenOptionFont: {
    fontSize: fp(25),
    fontFamily: SpoqaHanSansNeo.medium,
    color: 'black',
    marginLeft: wp(-3),
    marginBottom: hp(-10),
  },
  homeContentsScreenWrapper: {
    width: '100%',
    marginTop: hp(28),
    marginBottom: hp(230),
  },
  homeContentsScreenChoiceBarWrapper: {
    paddingLeft: wp(27),
    flexDirection: 'row',
  },
  homeContentsScreenChoiceBarFont: {
    paddingHorizontal: wp(16),
    paddingVertical: hp(8),
    backgroundColor: '#00C294',
    borderRadius: 30,
    fontSize: fp(16),
    color: '#FFFFFF',
    textAlign: 'center',
    fontFamily: SpoqaHanSansNeo.bold,
    marginRight: wp(7),
  },
  homeContentsScreenChoiceBarFontFocused: {
    paddingHorizontal: wp(16),
    paddingVertical: hp(8),
    borderRadius: 30,
    fontSize: fp(16),
    backgroundColor: '#F3F3F3',
    color: '#292929',
    textAlign: 'center',
    fontFamily: SpoqaHanSansNeo.bold,
    marginRight: wp(7),
  },
  homeContentsScreenParticipationWrapper: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 27,
  },
  homeContentsScreenParticipationText: {
    fontSize: fp(18),
    fontFamily: SpoqaHanSansNeo.regular,
    fontWeight: '600',
    color: '#292929',
    letterSpacing: wp(-1),
  },
  homeContentsScreenContentContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingLeft: wp(25),
  },
  homeContentsScreenContentWrapper: {
    paddingRight: wp(22),
    paddingBottom: hp(30),
  },
  homeContentsScreenContentDescription: {
    paddingTop: hp(8),
    fontSize: fp(16),
    fontFamily: SpoqaHanSansNeo.regular,
    color: '#000000',
    fontWeight: '600',
  },
  homeContentsScreenContentDateText: {
    fontSize: fp(15),
    fontFamily: SpoqaHanSansNeo.bold,
    color: '#000000',
    fontWeight: '600',
    letterSpacing: wp(-1),
  },
  homeContentsScreenContentTagWrapper: {
    maxWidth: wp(160),
    marginTop: hp(5),
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  homeContentsScreenContentTag: {
    paddingHorizontal: wp(3),
    paddingVertical: hp(2),
    marginRight: wp(8),
    marginBottom: hp(8),
    borderRadius: 3,
    fontSize: fp(12),
    fontFamily: SpoqaHanSansNeo.bold,
    color: '#000000',
    backgroundColor: '#F3F3F3',
  },
  homeContentsScreenChallengeButton: {
    borderColor: '#00DEA9',
    borderWidth: 1,
    borderRadius: 6,
    marginTop: hp(2),
    marginBottom: hp(-20),
  },
  homeContentsScreenChallengeButtonText: {
    paddingHorizontal: wp(120),
    paddingVertical: hp(11),
    color: '#00DEA9',
    fontSize: fp(16),
    letterSpacing: wp(-1),
    fontFamily: SpoqaHanSansNeo.regular,
  },
  homeContentsScreenMyChallengeContainer: {
    paddingHorizontal: wp(27),
  },
  homeContentsScreenMyChallengeWrapper: {
    marginTop: hp(50),
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  homeContentsScreenMyChallengeText: {
    paddingVertical: 12,
    fontSize: fp(20),
    fontFamily: SpoqaHanSansNeo.bold,
    color: '#000000',
  },
  homeContentsScreenMyChallengeViewMore: {
    fontSize: fp(14),
    fontFamily: SpoqaHanSansNeo.bold,
    color: '#000000',
  },
  homeContentsScreenMyChallengeMakeButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#EDFAF7',
    paddingHorizontal: 23,
    paddingVertical: 20,
    borderRadius: 5,
  },
  homeContentsScreenNewChallengeIcon: {
    width: 13,
    height: 13,
    marginLeft: wp(8),
    marginRight: wp(20),
  },
  homeContentsScreenNewChallengeText: {
    color: '#05C7A4',
    fontSize: fp(17),
    fontFamily: SpoqaHanSansNeo.regular,
  },
});
